import db from "./storage.ts";
import { Markdown, ListTypes } from "https://deno.land/x/deno_markdown/mod.ts";
import { moment } from "https://deno.land/x/moment/moment.ts";

async function export_entries_md(flag: any) {
  let markdown = new Markdown();

  const export_time = moment().format("MMMM_Do_YYYY_h_mm_a");
  const entries = await db.get("entries");
  const entries_to_export = entries.map(
    (e: any) => `[${e.created}]: ${e.text}.`
  );
  const tags = await db.get("tags");

  await markdown
    .header("Entries", 1)
    .header(export_time, 3)
    .list(entries_to_export, ListTypes.Ordered)
    .header("Tags", 1)
    .list(tags, ListTypes.UnOrdered)
    .quote("Generated by snippet-cli.")
    .write("./", `snippet_cli_export_${export_time}`);
}

async function export_entries_json(flag: any) {
  const export_time = moment().format("MMMM_Do_YYYY_h_mm_a");
  await Deno.copyFile(
    "./journals/default.json",
    `./snippet_cli_export_${export_time}.json`
  );
}

async function import_entries(flag: any) {
  await Deno.copyFile(flag, `./journals/default.json`);
}

const _impexp = {
  import_entries,
  export_entries_json,
  export_entries_md,
};

export default _impexp;
