import db from "./database.ts";
import { Markdown, ListTypes } from "https://deno.land/x/deno_markdown/mod.ts";
import { moment } from "https://deno.land/x/moment/moment.ts";

async function export_entries_md(flag: any) {
  let markdown = new Markdown();

  const export_time = moment().format("MMMM_Do_YYYY_h_mm_a");
  const entries = await db.get("entries");
  const entries_to_export = entries.map(
    (e: any) => `[${e.created}]: ${e.text}.`
  );

  await markdown
    .header("Entries", 1)
    .header(export_time, 3)
    .list(entries_to_export, ListTypes.Ordered)
    .quote("Generated by snippet-cli.")
    .write("./", `snippet_cli_export_${export_time}`);
}

async function export_entries_json(flag: any) {
  const export_time = moment().format("MMMM_Do_YYYY_h_mm_a");
  await Deno.writeTextFile(
    `snippet_cli_export_${export_time}.json`,
    JSON.stringify(await db.get("entries"))
  );
}

async function import_entries(flag: any) {
  await db.set("entries", JSON.parse(await Deno.readTextFile(flag)));
}

const _impexp = {
  import_entries,
  export_entries_json,
  export_entries_md,
};

export default _impexp;